-- ============================================================================
-- Fantasy Ekadashi — database schema
-- ============================================================================
-- Run this file in the Supabase SQL editor (or `supabase db push`) once, on
-- a fresh project. It creates all tables, RLS policies, the storage bucket
-- used for screenshots, and the helper RPCs the app calls from server actions.
--
-- Conventions:
--   * Times are stored as `timestamptz`.
--   * `ekadashi_date` is a `date` (no time component) representing the
--     calendar day in the league's timezone.
--   * IDs are uuid generated by `gen_random_uuid()`.
-- ============================================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- profiles: 1:1 with auth.users, adds display name + timezone preference.
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
    id           uuid primary key references auth.users(id) on delete cascade,
    display_name text not null,
    timezone     text not null default 'Asia/Kolkata',
    created_at   timestamptz not null default now()
);

-- Auto-create a profile row when a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, display_name, timezone)
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'display_name',
            split_part(new.email, '@', 1)
        ),
        coalesce(new.raw_user_meta_data ->> 'timezone', 'Asia/Kolkata')
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- ----------------------------------------------------------------------------
-- leagues
-- ----------------------------------------------------------------------------
create type league_status as enum ('open', 'active', 'completed');

create table if not exists public.leagues (
    id            uuid primary key default gen_random_uuid(),
    name          text not null,
    invite_code   text not null unique,
    created_by    uuid not null references public.profiles(id) on delete cascade,
    timezone      text not null default 'Asia/Kolkata',
    status        league_status not null default 'open',
    current_round int not null default 0,
    created_at    timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- league_members
-- ----------------------------------------------------------------------------
create table if not exists public.league_members (
    league_id     uuid not null references public.leagues(id) on delete cascade,
    user_id       uuid not null references public.profiles(id) on delete cascade,
    seed          int,
    eliminated_at timestamptz,
    joined_at     timestamptz not null default now(),
    primary key (league_id, user_id)
);

create index if not exists idx_members_user on public.league_members(user_id);

-- ----------------------------------------------------------------------------
-- matches
-- ----------------------------------------------------------------------------
create type match_status as enum (
    'scheduled',          -- created; awaiting Ekadashi
    'awaiting_submissions', -- Ekadashi day, players need to submit
    'pending_review',     -- both submitted, one disputed
    'completed',          -- winner decided
    'walkover'            -- one player missed the deadline
);

create table if not exists public.matches (
    id             uuid primary key default gen_random_uuid(),
    league_id      uuid not null references public.leagues(id) on delete cascade,
    round          int not null,
    ekadashi_date  date not null,
    player_a       uuid references public.profiles(id) on delete set null,
    player_b       uuid references public.profiles(id) on delete set null,  -- null = bye
    winner_id      uuid references public.profiles(id) on delete set null,
    status         match_status not null default 'scheduled',
    created_at     timestamptz not null default now()
);

create index if not exists idx_matches_league_round on public.matches(league_id, round);
create index if not exists idx_matches_players on public.matches(player_a, player_b);

-- ----------------------------------------------------------------------------
-- submissions
-- ----------------------------------------------------------------------------
create type submission_source as enum ('ocr', 'manual', 'mixed');

create table if not exists public.submissions (
    id                    uuid primary key default gen_random_uuid(),
    match_id              uuid not null references public.matches(id) on delete cascade,
    player_id             uuid not null references public.profiles(id) on delete cascade,
    screen_time_minutes   int not null check (screen_time_minutes >= 0 and screen_time_minutes <= 24 * 60),
    screenshot_path       text,   -- path inside the 'screenshots' storage bucket
    source                submission_source not null default 'manual',
    disputed              boolean not null default false,
    dispute_note          text,
    submitted_at          timestamptz not null default now(),
    unique (match_id, player_id)
);

create index if not exists idx_subs_match on public.submissions(match_id);

-- ============================================================================
-- Row-level security
-- ============================================================================

alter table public.profiles        enable row level security;
alter table public.leagues         enable row level security;
alter table public.league_members  enable row level security;
alter table public.matches         enable row level security;
alter table public.submissions     enable row level security;

-- Helper: is the current user a member of the given league?
create or replace function public.is_league_member(target_league uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.league_members
        where league_id = target_league and user_id = auth.uid()
    );
$$;

-- profiles --------------------------------------------------------------------
drop policy if exists "read own profile or shared league member" on public.profiles;
create policy "read own profile or shared league member"
    on public.profiles for select
    using (
        id = auth.uid()
        or exists (
            select 1
            from public.league_members m1
            join public.league_members m2 on m1.league_id = m2.league_id
            where m1.user_id = auth.uid() and m2.user_id = profiles.id
        )
    );

drop policy if exists "update own profile" on public.profiles;
create policy "update own profile"
    on public.profiles for update
    using (id = auth.uid())
    with check (id = auth.uid());

-- leagues ---------------------------------------------------------------------
drop policy if exists "members can read league" on public.leagues;
create policy "members can read league"
    on public.leagues for select
    using (
        created_by = auth.uid()
        or public.is_league_member(id)
    );

drop policy if exists "any user can create league" on public.leagues;
create policy "any user can create league"
    on public.leagues for insert
    with check (created_by = auth.uid());

drop policy if exists "creator can update league" on public.leagues;
create policy "creator can update league"
    on public.leagues for update
    using (created_by = auth.uid())
    with check (created_by = auth.uid());

-- league_members --------------------------------------------------------------
drop policy if exists "read members of leagues you belong to" on public.league_members;
create policy "read members of leagues you belong to"
    on public.league_members for select
    using (
        user_id = auth.uid()
        or public.is_league_member(league_id)
    );

drop policy if exists "self-insert when league open" on public.league_members;
create policy "self-insert when league open"
    on public.league_members for insert
    with check (
        user_id = auth.uid()
        and exists (
            select 1 from public.leagues
            where id = league_id and status = 'open'
        )
    );

drop policy if exists "leave league before it starts" on public.league_members;
create policy "leave league before it starts"
    on public.league_members for delete
    using (
        user_id = auth.uid()
        and exists (
            select 1 from public.leagues
            where id = league_id and status = 'open'
        )
    );

-- matches ---------------------------------------------------------------------
drop policy if exists "read matches in your leagues" on public.matches;
create policy "read matches in your leagues"
    on public.matches for select
    using (public.is_league_member(league_id));

-- (inserts/updates handled by service-role via server actions)

-- submissions -----------------------------------------------------------------
drop policy if exists "read submissions for your matches" on public.submissions;
create policy "read submissions for your matches"
    on public.submissions for select
    using (
        exists (
            select 1 from public.matches
            where id = submissions.match_id
            and public.is_league_member(matches.league_id)
        )
    );

drop policy if exists "insert your own submission" on public.submissions;
create policy "insert your own submission"
    on public.submissions for insert
    with check (
        player_id = auth.uid()
        and exists (
            select 1 from public.matches
            where id = match_id
            and (player_a = auth.uid() or player_b = auth.uid())
            and status in ('scheduled', 'awaiting_submissions')
        )
    );

drop policy if exists "update your own submission" on public.submissions;
create policy "update your own submission"
    on public.submissions for update
    using (player_id = auth.uid())
    with check (player_id = auth.uid());

-- ============================================================================
-- Storage bucket for screenshots
-- ============================================================================

-- Create a public bucket so screenshots can be displayed directly to opponents
-- via a public URL. (Files are still uploaded under a per-user folder; only
-- the URL is shared with the opponent.)
insert into storage.buckets (id, name, public)
values ('screenshots', 'screenshots', true)
on conflict (id) do nothing;

-- Storage RLS: users can upload only into their own folder.
drop policy if exists "users upload to own folder" on storage.objects;
create policy "users upload to own folder"
    on storage.objects for insert
    with check (
        bucket_id = 'screenshots'
        and (storage.foldername(name))[1] = auth.uid()::text
    );

drop policy if exists "public can read screenshots" on storage.objects;
create policy "public can read screenshots"
    on storage.objects for select
    using (bucket_id = 'screenshots');

drop policy if exists "users delete own screenshots" on storage.objects;
create policy "users delete own screenshots"
    on storage.objects for delete
    using (
        bucket_id = 'screenshots'
        and (storage.foldername(name))[1] = auth.uid()::text
    );
